// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "../components/Navbar";
// import Footer from "../components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Navbar></Navbar>
//         {children}
//         <Footer></Footer>
//       </body>
//     </html>
//   );
// }


// import { SessionProvider } from "next-auth/react";
// import Footer from '@/components/Footer';
// import './globals.css';
// import Navbar from '@/components/Navbar';

// export const metadata = {
//   title: 'SweetSlice',
//   description: 'Simple e-commerce demo with Next.js & DaisyUI',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <SessionProvider>
//           <Navbar />
//         <main className="min-h-[calc(100vh-200px)]">{children}</main>
//         <Footer />
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }
//  src/app/layout.jsx — SERVER COMPONENT (NO 'use client')

import Footer from '@/components/Footer';
import './globals.css';
import Navbar from '@/components/Navbar';
import SessionWrapper from '@/components/SessionWrapper'; // 👈 Import wrapper
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'SweetSlice',
  description: 'Simple e-commerce demo with Next.js & DaisyUI',
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* ✅ Wrap only the client part in SessionWrapper */}
        <SessionWrapper>
          <Navbar />
          <main className="min-h-[calc(100vh-200px)]">{children}</main>
          <Footer />
           <Toaster 
            position="top-center"
            toastOptions={{
              success: { duration: 3000 },
              error: { duration: 5000 },
            }}
          />
        </SessionWrapper>
       
{/* <div className="bg-gradient-to-r from-purple-100 to-indigo-50 dark:from-gray-900 dark:to-gray-800 min-h-screen">
  <SessionWrapper>
    <Navbar />
    
    <main className="min-h-[calc(100vh-200px)] text-gray-700 dark:text-gray-200">
      {children}
    </main>
    <Footer />
  </SessionWrapper>
</div> */}
      </body>
    </html>
  );
}